### PR TITLE
Changed rendering behavior of modals

### LINKED ISSUE #41: Usage of modals
The more i get into modals i think this is getting a huge pile of clusterfuck. Look at #37 #36 #28 for example. The main problem is that a modal is "always there". Even though it´s hidden, it has been rendered into the page. That leads to updating problems. Life would be easier if i would find a way to "reset" a template to it´s data-source, like "force-rerender" it. Example:

Imagine a modal with one input field bound to a reactive data source...
- open the modal
- edit the input field
- close / cancel the modal without saving

Reopening the modal would now show the edited data, because the reactive datasource has not been changed and so no template rerendering got triggered.

Any ideas on this?

### PR DESCRIPTION
**Pull request by devfoo-one**
fixes #41

I added a method `toggleModals()` and moved every modal into a separate template. Now the modal gets rendered when it´s called and gets removed when it´s closed. I think there are better (and more generic) solutions to this, but this should work for now. Please review and merge.

### CODE REVIEW

**Comment by Foaly** [comment]
I just took a look at it and it looks good. Everything works as expected. Just one quick question before merging. Why is the method called `toggleModal()` ? It doesn't actually toggle anything. Wouldn't `createModal` or something like that be more describtive?

**Comment by Foaly** [comment]
The pull request #62 should be merged instead of this one, so we get a clean commit history!

**Comment by devfoo-one** [comment]
@Foaly hm... jep `toggleModal()` is a little bit confusing. Actually it renders a modal into the DOM and toggles it. We could move the templates in separate files...

**Pull request merged**
